Settings: # overall settings
- 

MCCDAQ: # sensor DAC hats, Max 8 channels per hat
- hatID: 0 # DAQ hat address
  channelID: 0 # Channel ID on the DAQ hat, CH0H
  name: PGSO
  unit: psi
  type: PT # apply different regression formula + other things based on this? 
  calibration: [
    [0.99,0],
    [1.32,100],
    [1.70,200],
    [2.10,300],
    [2.51,400],
    [2.95,510],
    [3.34,600],
    [3.77,700],
    [4.08,775]
  ]

- hatID: 0
  channelID: 1 # CH1H
  name: PFT
  unit: psi
  type: PT
  calibration: [
    [1.98,0],
    [2.68,100],
    [3.53,200],
    [4.35,300],
    [5.19,400],
    [5.92,500],
    [6.74,600],
    [7.57,700],
    [8.25,800]
  ]

- hatID: 0
  channelID: 2 # CH2H
  name: PVO
  unit: psi
  type: PT
  calibration: [
    [1.97,0],
    [2.70,100],
    [3.53,200],
    [3.53,200],
    [4.35,300],
    [5.19,400],
    [5.92,500],
    [6.73,600],
    [7.57,700],
    [8.25,800]
  ]

- hatID: 0
  channelID: 3 # CH3H
  name: MOT
  unit: kg
  type: LC
  calibration: [
    [3.72,0],
    [5.98,4.5],
    [7.15,6.8]
  ]

- hatID: 0
  channelID: 4 # CH0L
  name: PGS
  unit: psi
  calibration: [
    [0.99,0],
    [1.32,100],
    [1.71,200],
    [2.11,300],
    [2.52,400],
    [2.96,510],
    [3.34,600],
    [3.78,700],
    [4.10,775]
  ]

- hatID: 0
  channelID: 5 # CH1L
  name: POT
  unit: psi
  calibration: [
    [2.01,0],
    [2.67,100],
    [3.43,200],
    [4.24,300],
    [5.04,400],
    [5.93,510],
    [6.69,600],
    [7.55,700],
    [8.17,775]
  ]

- hatID: 0
  channelID: 6 # CH2L
  name: PCC
  unit: psi
  calibration: [
    [2.00,0],
    [2.70,100],
    [3.55,200],
    [4.37,300],
    [5.18,400],
    [5.93,500],
    [6.74,600],
    [7.58,700],
    [8.26,800]
  ]

- hatID: 0
  channelID: 7 # CH3L
  name: MFT
  unit: kg
  type: LC
  calibration: [
  ]

- hatID: 1
  channelID: 0
  name: PFM
  unit: psi
  type: kg
  calibration: [
  ]

- hatID: 1
  channelID: 1
  name: CC-LC
  unit: kg
  type: LC
  calibration: [
  ]

relayBoard: # solenoid relay board - 16 channels

#- channelID: 1
#  name: MFV

#- channelID: 0
#  name: 

#- channelID: 2
#  name: 

#- channelID: 3
#  name: 

#- channelID: 4
#  name: 

#- channelID: 5
#  name: ch5

- channelID: 6
  name: IMC-G
  type: NC

#- channelID: 7
#  name: ch7

- channelID: 9
  name: SVGSD
  type: NC # Normally open (NO) or normally closed (NC)

- channelID: 8
  name: SVBVGS
  type: NC

- channelID: 11
  name: SVMOVP
  type: NC

#- channelID: 11
#  name: ch11

- channelID: 10
  name: SVPP   # injector purge, newly added
  type: NC

- channelID: 12
  name: SVFTV
  type: NC    # Fix later, should be NO but software should know

- channelID: 15
  name: SVOTV
  type: NC

- channelID: 14
  name: SVOTD
  type: NC

PCA9685: # servo driver board - 16 channels
# - channelID: 0
#   name: SERVO0
#   open_pos: 1300
#   close_pos: 1700


- channelID: 5
  name: MFV
  open_pos: 1800
  close_pos: 1050
  relayID: 1

- channelID: 6
  name: BVOTP
  open_pos: 2100
  #open_over:
  close_pos: 1020
  #close_over:
  relayID: 0

- channelID: 7
  name: BVFTP
  open_pos: 2050
  #open_over:
  close_pos: 1090
  #close_over:
  relayID: 3

- channelID: 8
  name: BVGSP
  open_pos: 850
  #open_over:
  close_pos: 1850
  #close_over: 
  relayID: 2

- channelID: 9
  name: BVGSO
  open_pos: 900
  #open_over:
  close_pos: 1970
  #close_over: 
  relayID: 5
