Settings: # overall settings
- 

MCCDAQ: # sensor DAC hats, Max 8 channels per hat
- hatID: 1 # DAQ hat address
  channelID: 0 # Channel ID on the DAQ hat, CH0H
  name: PGSO
  unit: psi
  type: PT # apply different regression formula + other things based on this? 
  calibration: [
    [0, 0], # [raw value, physical value]
    [1.8, 100] # example calibration points
  ]

- hatID: 1
  channelID: 1 # CH1H
  name: PFT
  unit: psi
  type: PT
  calibration: [
  ]

- hatID: 1
  channelID: 2 # CH2H
  name: PVO
  unit: psi
  type: PT
  calibration: [
  ]

- hatID: 1
  channelID: 3 # CH3H
  name: MOT
  unit: kg
  type: LC
  calibration: [
  ]

- hatID: 1
  channelID: 4 # CH0L
  name: PGS
  unit: psi
  calibration: [
  ]

- hatID: 1
  channelID: 5 # CH1L
  name: POT
  unit: psi
  calibration: [
  ]

- hatID: 0
  channelID: 6 # CH2L
  name: PCC
  unit: psi
  calibration: [
  ]

- hatID: 1
  channelID: 7 # CH3L
  name: MFT
  unit: kg
  type: LC
  calibration: [
  ]

# - hatID: 1
#   channelID: 0
#   name: MFT
#   unit: kg
#   type: LC
#   calibration: [
#   ]

# - hatID: 1
#   channelID: 1
#   name: CC-LC
#   unit: kg
#   type: LC
#   calibration: [
#   ]

relayBoard: # solenoid relay board - 16 channels
- channelID: 0
  name: BVOTP 
  relay_type: "NO"
  actuator_type: servo # actuator_type: solenoid, servo, poweredDevice, or poweredGpioDevice

- channelID: 1 # Shared with MFV
  name: IMC-V
  relay_type: "NO"
  actuator_type: poweredDevice # poweredDevice is a device that is powered on/off by a relay, like a pump or fan

- channelID: 6
  name: IMC-G 
  relay_type: "NO"
  actuator_type: poweredDevice

- channelID: 8
  name: SVBVGS
  relay_type: "NO"
  actuator_type: solenoid
  solenoid_type: NC

- channelID: 9
  name: SVGSD
  relay_type: 'NO' # Whether the relay is wired normally open (NO) or normally closed (NC) when unpowered
  actuator_type: solenoid
  solenoid_type: "NC" # Whether the solenoid is normally open (NO) or normally closed (NC) when unpowered

- channelID: 11
  name: SVMOVP
  relay_type: "NO"
  actuator_type: solenoid
  solenoid_type: "NC"

- channelID: 10
  name: SVPP   # injector purge, newly added
  relay_type: "NO"
  actuator_type: solenoid
  solenoid_type: NC

- channelID: 12
  name: SVFTV
  relay_type: NC
  actuator_type: solenoid
  solenoid_type: "NO"

- channelID: 15
  name: SVOTV
  relay_type: NC
  actuator_type: solenoid
  solenoid_type: "NO"

- channelID: 14
  name: SVOTD
  type: NC
  relay_type: "NO"
  actuator_type: solenoid
  solenoid_type: NC

PCA9685: # servo driver board - 16 channels
- channelID: 5
  name: MFV
  states: 2 # number of states, 2 for open/close valve, 3 for 3-way valve, etc.
  open_pos: 1800
  close_pos: 1050
  relayID: 1

- channelID: 6
  name: BVOTP
  open_pos: 2100
  close_pos: 1020
  relayID: 0

- channelID: 7
  name: BVFTP
  open_pos: 2050
  close_pos: 1090
  relayID: 3

- channelID: 8
  name: BVGSP
  open_pos: 850
  close_pos: 1900
  relayID: 2

- channelID: 9
  name: BVGSO
  open_pos: 900
  close_pos: 1970
  relayID: 5


GPIOs: # General Purpose Input/Output pins
- pinID: 5
  name: GPIO5
  mode: input # input or output
  default_state: high # low or high
  relayID: 4 # Optional, if the device is powered by a relay

- pinID: 6
  name: GPIO6
  mode: input # input or output
  default_state: high # low or high

- pinID: 17
  name: TEST-DEVICE
  mode: output # input or output
  default_state: low # low or high
  relayID: 6 # Optional, if the device is powered by a relay

- pinID: 27
  name: GPIO27
  mode: output # input or output
  default_state: low # low or high

- pinID: 22
  name: GPIO22
  mode: output # input or output
  default_state: high # low or high
